import { useRouter } from 'next/router'
import Head from 'next/head'
import Script from 'next/script'
import Header from '@/components/HeaderLayout'
import Button from '@/components/Button/Button'
import { useEffect } from 'react'
import { ChakraProvider, Spinner } from '@chakra-ui/react'
import useUser, { USER_STATES } from '@/hooks/useUser'
import GitHub from '@/components/Icons/Github'

// const inter = Inter({ subsets: ['latin'] });

export default function Home () {
  const router = useRouter()
  const { user, handleSingIn } = useUser()

  useEffect(() => {
    user && router.replace('/home')
  }, [user])

  return (
    <ChakraProvider>
      <main className='relative m-auto'>
        <Head>
          <title>Devter ♣</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
          <div className='flex flex-col justify-center items-center'>
            <Header links={[{ name: 'home', url: '/home' }, { name: 'timeline', url: '/timeline' }, { name: 'user', url: '/user-data' }]}>
              {'< talk about development with developers />'}
            </Header>
            {user === USER_STATES.NOT_LOGGED && (
              <div className='mt-3'>
                <Button handleClick={handleSingIn}>
                  <GitHub fill="#fff" width={24} height={24} /> Loguearse con Github
              </Button>
              </div>
            )}
            {user === USER_STATES.NOT_KNOWN && (
              <div className='mt-7'>
                <Spinner size='xl' color='blue.600' />
              </div>
            )}
          </div>
        <Script
          src='https://kit.fontawesome.com/71feeb67fe.js'
          crossOrigin='anonymous'
        />
      </main>
    </ChakraProvider>
  )
}
