import { useRouter } from 'next/router'
import Head from 'next/head'
import Script from 'next/script'
import MobileWrapper from '@/components/MobileWrapper'
import Header from '@/components/HeaderLayout'
import Button from '@/components/Button/Button'
import { loginWithGithub, onAuthStateChangeOfUser } from '@/firebase/client'
import { useEffect, useState } from 'react'
import { ChakraProvider, Spinner } from '@chakra-ui/react'

// const inter = Inter({ subsets: ["latin"] });

const USER_STATES = {
  NOT_LOGGED: null,
  NOT_KNOWN: undefined
}

export default function Home () {
  const router = useRouter()
  const [user, setUser] = useState(USER_STATES.NOT_LOGGED)

  useEffect(() => {
    onAuthStateChangeOfUser(setUser)
  }, [])

  useEffect(() => {
    user && router.replace('/home')
  }, [user])

  const handleSingIn = () => {
    loginWithGithub()
      .then((res) => setUser(res))
      .catch((err) => console.log(err))
  }

  return (
    <ChakraProvider>
      <main className="relative">
        <Head>
          <title>Devter ♣</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <MobileWrapper>
          <div className="flex flex-col justify-center items-center">
            <Header links={[{ name: 'timeline', url: '/timeline' }, { name: 'user', url: '/user-data' }]}>
              {'< talk about development with developers />'}
            </Header>
            {user === USER_STATES.NOT_LOGGED && (
              <div className="mt-3">
                <Button handleClick={handleSingIn}>
                <i className="fa-brands fa-github"></i> Loguearse con Github
              </Button>
              </div>
            )}
            {user === USER_STATES.NOT_KNOWN && (
              <div className="mt-7">
                <Spinner size="xl" color="blue.600" />
              </div>
            )}
          </div>
        </MobileWrapper>
        <Script
          src="https://kit.fontawesome.com/71feeb67fe.js"
          crossOrigin="anonymous"
        />
      </main>
    </ChakraProvider>
  )
}
