import Head from "next/head";
import Script from "next/script";
// import { Inter } from '@next/font/google'
// import styles from "@/styles/Home.module.css";
import Header from "@/components/HeaderLayout";
import MobileWrapper from "@/components/MobileWrapper";
import Button from "@/components/Button/Button";
import { loginWithGithub, onAuthStateChangeOfUser } from "@/firebase/client";
import UserAvatar from "@/components/UserAvatar/UserAvatar";
import { useEffect, useState } from "react";
import { ChakraProvider } from "@chakra-ui/react";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [user, setUser] = useState(null);

  useEffect(() => {
    onAuthStateChangeOfUser(setUser);
  }, []);

  const handleSingIn = () => {
    loginWithGithub()
      .then((res) => setUser(res))
      .catch((err) => console.log(err));
  };

  return (
    <ChakraProvider>
      <main className="relative">
        <Head>
          <title>Devter ♣</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <MobileWrapper>
          <Header links={[{ name: "timeline", url: "/timeline" }]}>
            {"< talk about development with developers />"}
          </Header>
          {user === null && (
            <Button handleClick={handleSingIn}>
              <i className="fa-brands fa-github"></i> Loguearse con Github
            </Button>
          )}
          <UserAvatar user={user} />
        </MobileWrapper>
        <Script
          src="https://kit.fontawesome.com/71feeb67fe.js"
          crossOrigin="anonymous"
        />
      </main>
    </ChakraProvider>
  );
}
